### ISSUE TITLE
BUG: no error handler for file parsing error

### ISSUE THREAD

**Issue by adaagava** [soramitsu/adar#112]
If I load the file that can't be parsed, the loading process freezes and there is no law to continue.
The error message should be returned.
<img width="673" alt="Screenshot 2022-12-22 at 18 49 37" src="https://user-images.githubusercontent.com/109272254/209196048-c3937862-b08e-4439-bd65-22d1d7db0084.png">

**Comment by artemb0** [comment]
https://www.figma.com/file/fviBkasLFmcsvciy7K0qCq/ADAR-X-PSWAP?node-id=183%3A7510&t=nzSN5NtWBjAkfWWi-1
