### ISSUE TITLE
There in no further step if re-run failed

### ISSUE THREAD

**Issue by adaagava** [soramitsu/adar#171]
We don't have any opportunity to get the pdf report and to finish the flow is one of the transactions continuously failed and re-run doesn't help. Looks like we need a button "finish anyway" or something similar.
<img width="1385" alt="Screenshot 2022-12-14 at 16 29 24" src="https://user-images.githubusercontent.com/109272254/207843885-6a5427f5-413e-4809-99d4-222df867de24.png">

**Comment by artemb0** [comment]
added designs for this issue:
[**https://www.figma.com/file/fviBkasLFmcsvciy7K0qCq/ADAR-X-PSWAP?node-id=174%3A7739&t=YVJ3cHPYmH8uLFZY-1**](https://www.figma.com/file/fviBkasLFmcsvciy7K0qCq/ADAR-X-PSWAP?node-id=174%3A7739&t=YVJ3cHPYmH8uLFZY-1)
